name: Snyk Delta CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  snyk-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: Install Snyk and snyk-delta
      run: |
        npm install -g snyk
        npm install -g snyk-delta

    - name: Snyk Auth
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Run Snyk Test
      run: snyk test

    - name: Run snyk-delta to compare changes
      run: snyk-delta
